[server]
address = "127.0.0.1:8000" # адрес куда транслируются запросы
rm = '5/m' # дефолтный рэйт лимитер (при server и all_path)
rrm = '1/m'
all_path = true # для тех роутов, которые не прописаны в конфиге - использовать настройки сервера 

[[route]] # с помощью этой дерективы обозначают роутер
path = "/api/v1/products" 
rm = "5/m" # сколько запросов примет 
rrm = "1/m" # сколько запросов РЕАЛЬНО уйдет на сервер
active = true

[[route]]
path = "/api/v1/users"
rm = "10/m"
rrm = 'server' # если вообще не указан - то сразу все запросы без rrm
active = false # обслуживать этот api