[server]
address = "127.0.0.1:8000"
rm = '5/m'
rrm = '1/m'
queue = false
all_path = true

[[route]]
path = "/api/v1/products"
rm = "5/m"
rrm = "1/m"
queue = false
code = 202
active = true

[[route]]
path = "/api/v1/users"
rm = "10/m"
rrm = 'server'
active = false
