services:
  redis:
    image: redis:7.4-alpine
    container_name: my-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--no-auth-warning", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  aegis:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: aegis
    restart: unless-stopped
    command: uv run gunicorn src.api.router:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:6378
    ports:
      - '6378:6378'
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:
    driver: local