name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Add pass for Redis
        run: |
          mv .env.example .env
      - name: Set dependencies
        run: |
          uv sync
      - name: Testing code using pytest
        run: |
          uv run pytest -s -vv
